# Generated by Django 4.2.7 on 2023-11-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elabweb', '0002_book_isbn_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='publication_year',
        ),
    ]
