# Generated by Django 4.2.7 on 2023-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabweb', '0003_rename_publication_date_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(null=True, upload_to='book_files/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=15),
        ),
    ]
