# Generated by Django 4.2.7 on 2023-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabweb', '0004_book_book_file_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
