# Generated by Django 4.2.7 on 2023-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabweb', '0005_remove_book_genre_book_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Amount',
            field=models.CharField(max_length=100),
        ),
    ]
